apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-training-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      job-name: model-training-cronjob
  endpoints:
    - port: 8001
      interval: 30s
