apiVersion: v1
kind: Service
metadata:
  name: model-training-service
spec:
  selector:
    job-name: model-training-cronjob
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
