apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-serving-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: model-serving
  endpoints:
    - port: 9100
      interval: 30s
