apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
spec:
  selector:
    app: model-serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: LoadBalancer
